### ISSUE TITLE
Defining a VM and a set of OPCODES

### ISSUE THREAD

**Issue by xvw** [marigold-dev/chusai#10]
- [ ] using a ligo/ocaml serialization strategy for sending messages (and originate smart contract)
- [ ] defining the set of opcodes for dealing with transaction
- [ ] Writting the minimal shhell (deposit, withdraw and transaction opcodes)

## Acceptance Criteria
- [ ] Having a state definition 
- [ ] Being able to hash a state
- [ ] Having the documentation of opcodes
- [ ] Having a end-to-end scenario

## Tasks
- [x] 10-1 (C2) Implement serialization/deserialization between OCaml and Ligo of the state as Michelson binary format for primitive types
- [x] 10-2.1 (OD) Implement MerkelizedTreeMap in ocaml
- [x] 10-2.2 [] (OD) Implement MerkelizedTreeMap verification in ocaml
- [ ] 10-3 translate verification algorithm to Ligo
- [ ] 10-4 implement deposit/withdraw/transfer in VM

related to #1
